version: '3.8'
services:
  main_graphql_api_server:
    image: node
    ports:
      - "4000:4000"
    environment:
      MEDIA_QUALITY_ENHANCEMENT_SERVICE_ADDR: media_quality_enhancement_service:4001
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./memories_db/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
  media_quality_enhancement_service:
    image: media_quality_enhancement_service:b0.1
    ports:
      - "4001:4001"
    volumes:
      - ./media_data/:/media_data/
    environment:
      ISR_SERVICE_ADDR: image_super_resolution_service:4103
      VIDEO_PREPROCESSING_SERVICE_ADDR: video_preprocessing_service:4201
      VIDEO_COLORIZATION_SERVICE_ADDR: video_colorization_service:4202
      VSR_VFI_SERVICE_ADDR: vsr_vfi_service:4203
  image_super_resolution_service:
    image: image_super_resolution_service:b0.1
    ports:
      - "4103:4103"
    volumes:
      - ~/media_data/:/media_data/
    environment:
      - NVIDIA_VISIBLE_DEVICES=1

  video_preprocessing_service:
    image: video_preprocessing_service:b0.1
    ports:
      - "4201:4201"
    volumes:
      - ~/media_data/:/media_data/
  video_colorization_service:
    image: video_colorization_service:b0.1
    ports:
      - "4202:4202"
    volumes:
      - ~/media_data/:/media_data/
    environment:
      - NVIDIA_VISIBLE_DEVICES=2
  vsr_vfi_service:
    image: vsr_vfi_service:b0.1
    ports:
      - "4203:4203"
    volumes:
      - ~/media_data/:/media_data/
    environment:
      - NVIDIA_VISIBLE_DEVICES=3